openapi: 3.0.0
info:
  version: 1.0.0
  title: Players Service API

tags:
  - name: player

paths:

  /player:
    post:
      summary: Create a player
      operationId: createPlayer
      tags:
        - player
      responses:
        "201":
          description: Player was created
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

components:

  responses:

    DefaultErrorResponse:
      description: Unexpected error
      content:
        "*/*":
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Error"

  schemas:

    Error:
      type: "object"
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string