openapi: 3.0.0
info:
  version: 1.0.0
  title: Players Service API

tags:
  - name: players

paths:

  /players:
    post:
      summary: Create a player
      operationId: createPlayer
      tags:
        - players
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/CreatePlayerRequest"
      responses:
        "201":
          description: Player was created
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
    get:
      summary: Get all players
      operationId: getAllPlayers
      parameters:
        - name: position
          in: query
          description: Position of the player
          required: false
          schema:
            $ref: "#/components/schemas/PlayerPositionParam"
        - name: size
          in: query
          description: Number of players to return
          required: false
          schema:
            type: integer
            format: int32
            default: 10
        - name: page
          in: query
          description: Page number of the players to return
          required: false
          schema:
            default: 0
            type: integer
            format: int32
      tags:
        - players
      responses:
        "200":
          description: Players were retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/responses/PlayerResponse"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /players/generate:
    post:
      summary: Generate a number of players
      operationId: generatePlayer
      tags:
        - players
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/GeneratePlayersRequest"
      responses:
        "201":
          description: Players were generated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/responses/PlayerResponse"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /player-position-tendencies:
    get:
      summary: Get all player position tendencies
      operationId: getAllPlayerPositionTendencies
      tags:
        - player-position-tendencies
      responses:
        "200":
          description: Player position tendencies were retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/responses/PlayerPositionTendencyResponse"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

  /player-position-tendencies/{position}:
    get:
      summary: Get the tendency of a position
      operationId: getPlayerPositionTendency
      parameters:
        - name: position
          in: path
          description: Position of the player
          required: true
          schema:
            $ref: "#/components/schemas/PlayerPositionParam"
      tags:
        - player-position-tendencies
      responses:
        "200":
          description: Player position tendency was retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/responses/PlayerPositionTendencyResponse"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
    patch:
      summary: Update the tendency of a position
      operationId: updatePlayerPositionTendency
      parameters:
        - name: position
          in: path
          description: Position of the player
          required: true
          schema:
            $ref: "#/components/schemas/PlayerPositionParam"
      tags:
        - player-position-tendencies
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/UpdatePlayerPositionTendencyRequest"
      responses:
        "200":
          description: Player position tendency was updated
          content:
            application/json:
              schema:
                $ref: "#/components/responses/PlayerPositionTendencyResponse"
        default:
          $ref: "#/components/responses/DefaultErrorResponse"

components:

  requestBodies:
    CreatePlayerRequest:
      description: Create player request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreatePlayerRequest"

    GeneratePlayersRequest:
      description: Generate players request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/GeneratePlayersRequest"

    UpdatePlayerPositionTendencyRequest:
      description: Update player position tendency request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UpdatePlayerPositionTendencyRequest"

  responses:

    PlayerResponse:
      description: Player response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PlayerResponse"

    PlayerPositionTendencyResponse:
      description: Player position tendency response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PlayerPositionTendencyResponse"

    DefaultErrorResponse:
      description: Unexpected error
      content:
        "*/*":
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Error"

  schemas:

    PlayerSkillParam:
      type: string
      enum:
        - SCORE
        - OFFENSIVE_POSITION
        - BALL_CONTROL
        - PASSING
        - CO
        - TACKLING
        - DEFENSE_POSITION

    PlayerPositionParam:
      type: string
      enum:
        - DEFENDER
        - MIDDLE
        - FORWARD
      example: FORWARD

    CreatePlayerRequest:
      type: object
      properties:
        points:
          type: integer
          format: int32
          minimum: 1
          maximum: 700
          example: 350
        age:
          type: integer
          format: int32
          minimum: 15
          maximum: 33
          example: 21
        position:
          $ref: "#/components/schemas/PlayerPositionParam"

    GeneratePlayersRequest:
      type: object
      properties:
        numberOfPlayers:
          type: integer
          format: int32
          minimum: 1
          maximum: 1000
          example: 10

    UpdatePlayerPositionTendencyRequest:
      type: object
      example: { "SCORE": 5 }
      additionalProperties:
        type: string
        properties:
          code:
            $ref: "#/components/schemas/PlayerSkillParam"
          text:
            type: integer
            format: int32
            minimum: 0
            example: 5

    PlayerResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 1a2b3c4d-5e6f-7g8h-9i0j-1k2l3m4n5o6p
        age:
          type: integer
          format: int32
          minimum: 15
          maximum: 33
          example: 21
        name:
          type: string
          example: John Doe
        position:
          $ref: "#/components/schemas/PlayerPositionParam"
        actualSkills:
          type: object
          example: { "SCORE": 50 }
          additionalProperties:
            type: string
            properties:
              code:
                $ref: "#/components/schemas/PlayerSkillParam"
              text:
                type: integer
                format: int32
                minimum: 0
                maximum: 100
                example: 50

    PlayerPositionTendencyResponse:
      type: object
      properties:
        position:
          $ref: "#/components/schemas/PlayerPositionParam"
        tendencies:
          type: object
          example: { "SCORE": 5 }
          additionalProperties:
            type: string
            properties:
              code:
                $ref: "#/components/schemas/PlayerSkillParam"
              text:
                type: integer
                format: int32
                minimum: 0
                example: 5
        default:
          type: boolean

    Error:
      type: "object"
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
