server:
  port: 8083
  error:
    include-message: always

spring:
  application:
    name: match-service

springdoc:
  version: "@springdoc.version@"
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
