name: "Tag version"
description: "Returns the version of the git tag"

outputs:
  version:
    description: "Git tag version"
    value: ${{ steps.version_step.outputs.version }}

runs:
  using: "composite"

  steps:
    - name: Version generation
      id: version_step
      run: echo "version=5" >> $GITHUB_OUTPUT
      shell: bash
