name: "Tag version"
description: "Returns the version of the git tag"

inputs:
  RELEASE:
    description: If not release, default version is latest
    default: "false"

outputs:
  version:
    description: "Git tag version"
    value: ${{ steps.version_step.outputs.version }}

runs:
  using: "composite"

  steps:
    - name: Version generation
      run: |
        if [[ ${{ inputs.RELEASE }} == true ]]; then
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        else
          echo "VERSION=latest" >> $GITHUB_ENV
        fi
      shell: bash
