name: "NPM Build"
description: "Builds a npm fe"

inputs:
  PATH:
    required: true
    description: "The path of the fe to built"
  FE_NAME:
    required: true
    description: "The name of the fe to built"
  AWS_ECR_URI:
    required: true
    description: "AWS_ECR_URI"
  AWS_CICD_ACCESS_KEY:
    required: true
    description: "AWS_CICD_ACCESS_KEY"
  AWS_CICD_SECRET_ACCESS_KEY:
    required: true
    description: "AWS_CICD_SECRET_ACCESS_KEY"
  SLACK_CICD_WEBHOOK:
    required: true
    description: "SLACK_CICD_WEBHOOK"

runs:
  using: "composite"

  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v32
      with:
        files: |
          ${{ inputs.PATH }}/**

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "npm"
        cache-dependency-path: ${{ inputs.PATH }}/package-lock.json

    - name: Build
      id: build
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        cd ${{ inputs.PATH }}
        npm run dev
      shell: bash

    - name: Generate ECR Variables
      id: ecr_variables
      if: steps.build.outcome == 'success'
      run: |
        echo "ECR_IMAGE_NAME=${{ inputs.AWS_ECR_URI }}/${{ inputs.FE_NAME }}:latest" >> $GITHUB_ENV
      shell: bash

    - name: AWS ECR Configure
      id: ecr_configure
      if: steps.build.outcome == 'success'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_CICD_ACCESS_KEY }}
        aws-secret-access-key: ${{ inputs.AWS_CICD_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login_ecr
      if: steps.ecr_configure.outcome == 'success'
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      id: ecr_push
      if: steps.login_ecr.outcome == 'success'
      run: |
        cd ${{ inputs.PATH }}
        docker build -t ${{ env.ECR_IMAGE_NAME }} .
        docker push ${{ env.ECR_IMAGE_NAME }}
      shell: bash

    - name: Slack Notification
      if: steps.ecr_push.outcome == 'success'
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ci-cd
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github-actions.s3.eu-west-1.amazonaws.com/Octocat.png
        SLACK_WEBHOOK: ${{ inputs.SLACK_CICD_WEBHOOK }}
        SLACK_USERNAME: GitHub Actions
        SLACK_TITLE: Built ${{ inputs.FE_NAME }}
        SLACK_FOOTER: "CI up to ECR successfully finished"
        MSG_MINIMAL: actions url, commit
