name: "Maven Build"
description: "Builds a mvn service"

inputs:
  PATH:
    required: true
    description: "The path of the service to built"
  SERVICE_NAME:
    required: true
    description: "The name of the service to built"
  AWS_ECR_URI:
    required: true
    description: "AWS_ECR_URI"
  AWS_CICD_ACCESS_KEY:
    required: true
    description: "AWS_CICD_ACCESS_KEY"
  AWS_CICD_SECRET_ACCESS_KEY:
    required: true
    description: "AWS_CICD_SECRET_ACCESS_KEY"
  SLACK_CICD_WEBHOOK:
    required: true
    description: "SLACK_CICD_WEBHOOK"
  DOCKER_IMAGE_GENERATION:
    required: false
    description: "DOCKER_IMAGE_GENERATION"
    default: "true"

runs:
  using: "composite"

  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v32
      with:
        files: |
          ${{ inputs.PATH }}/**

    - uses: actions/setup-java@v3
      with:
        distribution: "corretto"
        java-version: "17"
        cache: "maven"

    - name: Build
      id: build
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        cd ${{ inputs.PATH }}
        mvn clean install -U -DskipTests=true
      shell: bash

    - name: Generate ECR Variables
      id: ecr_variables
      if: |
        steps.build.outcome == 'success' && 
        '${{ inputs.DOCKER_IMAGE_GENERATION }}' == 'true'
      run: |
        echo "ECR_IMAGE_NAME=${{ inputs.AWS_ECR_URI }}/${{ inputs.SERVICE_NAME }}:latest" >> $GITHUB_ENV
      shell: bash

    - name: AWS ECR Configure
      id: ecr_configure
      if: steps.ecr_variables.outcome == 'success'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_CICD_ACCESS_KEY }}
        aws-secret-access-key: ${{ inputs.AWS_CICD_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login_ecr
      if: steps.ecr_configure.outcome == 'success'
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      id: ecr_push
      if: steps.login_ecr.outcome == 'success'
      run: |
        cd ${{ inputs.PATH }}
        docker build -t ${{ env.ECR_IMAGE_NAME }} .
        docker push ${{ env.ECR_IMAGE_NAME }}
      shell: bash

    - name: Slack Notification
      if: |
        steps.ecr_push.outcome == 'success' || 
        (${{ inputs.DOCKER_IMAGE_GENERATION }} == 'false' && steps.build.outcome == 'success')
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ci-cd
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github-actions.s3.eu-west-1.amazonaws.com/Octocat.png
        SLACK_WEBHOOK: ${{ inputs.SLACK_CICD_WEBHOOK }}
        SLACK_USERNAME: GitHub Actions
        SLACK_TITLE: Built ${{ inputs.SERVICE_NAME }}
        SLACK_FOOTER: "CI successfully finished"
        MSG_MINIMAL: actions url, commit
