name: 'Maven Build'

inputs:
  path:  # path to the project to build
    required: true

runs:

  using: "composite"

  steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v32
      with:
        files: |
          services/auth-service/**

    - name: Build
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        cd ${{ inputs.path }}
        mvn clean install -U
      shell: bash