name: 'Maven Build'

inputs:
  path:  # path to the project to build
    required: true

runs:

  using: "composite"

  steps:

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v32
      with:
        files: |
          services/auth-service/**

    - name: Build
      run: |
        cd ${{ inputs.path }}
        mvn clean install -U
      shell: bash