name: 'Maven Build'

inputs:
  path:  # path to the project to build
    required: true

runs:

  using: "composite"

  steps:

    - name: Build
      if: steps.changes.outputs.src == 'true'
      run: |
        cd ${{ inputs.path }}
        mvn clean install -U
      shell: bash