name: "Maven Build"
description: "Builds a mvn service"

inputs:
  path: # path to the project to build
    required: true
    description: "The path of the service to built"
  service-name:
    required: true
    description: "The name of the service to built"
  ecr-uri:
    required: true
    description: "AWS ECR URI"
  cicd-accesskey:
    required: true
    description: "AWS CI CD user access key"
  cicd-secretaccesskey:
    required: true
    description: "AWS CI CD user secret access key"

runs:
  using: "composite"

  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v32
      with:
        files: |
          ${{ inputs.path }}/**

    - name: Build
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        cd ${{ inputs.path }}
        mvn clean install -U
      shell: bash

    - name: Generate ECR Variables
      if: success()
      run: |
        echo ${{ inputs.ecr-uri }}/${{ inputs.service-name }}:latest >> $GITHUB_ENV
      shell: bash

    - name: AWS ECR Configure
      if: success()
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.cicd-accesskey }}
        aws-secret-access-key: ${{ inputs.cicd-secretaccesskey }}
        aws-region: eu-west-1

    - name: Build and Push to ECR
      if: success()
      run: |
        aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{ inputs.ecr-uri }}
        cd ${{ inputs.path }}
        docker build -t ${{ env.ECR_IMAGE_NAME }} .
        docker push ${{ env.ECR_IMAGE_NAME }}
      shell: bash

    - name: Slack Notification
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ci-cd
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: s3://github-actions/Octocat.png
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
        SLACK_USERNAME: GitHub Actions
        SLACK_TITLE: Built ${{ inputs.service-name }}
        SLACK_FOOTER: "8=D"
