openapi: 3.0.0
info:
  version: 1.0.0
  title: Match Service API

tags:
  - name: match

paths:

  /match:
    post:
      summary: Create a match
      operationId: createMatch
      tags:
        - match
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/CreateMatchRequest"
      responses:
        "201":
          description: Match was created
        default:
          $ref: "#/components/responses/DefaultErrorResponse"
components:

  requestBodies:

    CreateMatchRequest:
      description: Create match request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateMatchRequest"

  responses:

    DefaultErrorResponse:
      description: Unexpected error
      content:
        "*/*":
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Error"

  schemas:

    Tactic:
      type: string
      example: DOUBLE_TEAM
      enum:
        - DOUBLE_TEAM
        - MAN_ON_MAN
        - ZONE
        - COUNTER_ATTACK
        - POSSESSION_CONTROL
        - TIKA_TAKA
        - WING_PLAY
        - CATENACCIO
        - ROUTE_ONE
        - OFFSIDE_TRAP

    HorizontalPressure:
      type: string
      example: NO_HORIZONTAL_FOCUS
      enum:
        - SWARM_CENTRE
        - SWARM_FLANKS
        - NO_HORIZONTAL_FOCUS

    VerticalPressure:
      type: string
      example: NO_VERTICAL_FOCUS
      enum:
        - MID_PRESSURE
        - LOW_PRESSURE
        - NO_VERTICAL_FOCUS

    Error:
      type: "object"
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string

    CreateMatchRequest:
      type: object
      properties:
        home:
          type: object
          properties:
            id:
              type: string
              example: id
            modifiers:
              $ref: "#/components/schemas/Modifiers"
        away:
          type: object
          properties:
            id:
              type: string
              example: id
            modifiers:
              $ref: "#/components/schemas/Modifiers"

    Modifiers:
      type: object
      properties:
        tactic:
          $ref: "#/components/schemas/Tactic"
        horizontalPressure:
          $ref: "#/components/schemas/HorizontalPressure"
        verticalPressure:
          $ref: "#/components/schemas/VerticalPressure"
