openapi: 3.0.0
info:
  version: 1.0.0
  title: Match Service API

tags:
  - name: match

paths:

  /match:
    post:
      summary: Create a match
      operationId: createMatch
      tags:
        - match
      requestBody:
        description: Create match request
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                home:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                away:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int63
                      example: 1
      responses:
        "201":
          description: Match was created
        default:
          description: Unexpected error
          content:
            "*/*":
              schema:
                type: array
                items:
                  type: "object"
                  required:
                    - code
                    - message
                  properties:
                    code:
                      type: integer
                      format: int32
                    message:
                      type: string