server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: player-service

springdoc:
  version: '@springdoc.version@'
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true