server:
  port: ${SERVER_PORT}

spring:
  application:
    profiles:
      active: 'local'
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      database: ${DB_DATABASE}

player:
  persistence:
    adapter: ${PLAYER_PERSISTENCE_ADAPTER}
    cache:
      ttl: ${PLAYER_PERSISTENCE_CACHE_TTL}
      size: ${PLAYER_PERSISTENCE_CACHE_SIZE}
      cleanup-interval: ${PLAYER_PERSISTENCE_CLEANUP_CACHE_INTERVAL}
