server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: player-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: root
      database: admin
      auto-index-creation: true
  kafka:
    bootstrap-servers: http://localhost:9092
    linger-ms: 10
    group-id: player-service

springdoc:
  version: "@springdoc.version@"
  api-docs:
    path: /api-docs
  swagger-ui:
    use-root-path: true
  show-actuator: true

kafka:
  topics:
    auth-signup: AuthSignup

player:
  persistence:
    adapter: cache # Change to 'mongodb' to use MongoDB
    cache:
      ttl: 60000 # in milliseconds
      size: 1000
      cleanup-interval: 1000 # in milliseconds
