version: '3'

services:

  ##################
  ## Auth Service ##
  ##################

  auth-service-mongodb:
    image: mongo:5.0
    container_name: auth-service-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root

  auth-service:
    image: 040156513434.dkr.ecr.eu-west-1.amazonaws.com/auth-service:latest
    ports:
      - 8081:8081
    container_name: auth-service
    env_file:
      - ../config/common.env
      - ../config/auth-service.env

  #####################
  ## Gateway Service ##
  #####################

  gateway-service:
    image: 040156513434.dkr.ecr.eu-west-1.amazonaws.com/gateway-service:latest
    ports:
      - 8080:8080
    container_name: gateway-service
    env_file:
      - ../config/common.env
      - ../config/gateway-service.env
