version: '3'

services:

  ##############
  ## Local DB ##
  ##############

  local-mongodb:
    image: mongo:5.0
    container_name: local-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  ##################
  ## Auth Service ##
  ##################

  auth-service:
    image: 040156513434.dkr.ecr.eu-west-1.amazonaws.com/auth-service:latest
    ports:
      - 8081:8081
    container_name: auth-service
    env_file:
      - ../config/common.env
      - ../config/auth-service.env
    depends_on:
      local-mongodb:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent auth-service:8081/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5

  #####################
  ## Gateway Service ##
  #####################

  gateway-service:
    image: 040156513434.dkr.ecr.eu-west-1.amazonaws.com/gateway-service:latest
    ports:
      - 8080:8080
    container_name: gateway-service
    env_file:
      - ../config/common.env
      - ../config/gateway-service.env
    depends_on:
      auth-service:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5

  ####################
  ## Player Service ##
  ####################

  player-service:
    image: 040156513434.dkr.ecr.eu-west-1.amazonaws.com/player-service:latest
    ports:
      - 8082:8082
    container_name: player-service
    env_file:
      - ../config/common.env
      - ../config/player-service.env
    depends_on:
      gateway-service:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5

  ###################
  ## Match Service ##
  ###################

  match-service:
    image: 040156513434.dkr.ecr.eu-west-1.amazonaws.com/match-service:latest
    ports:
      - 8083:8083
    container_name: match-service
    env_file:
      - ../config/common.env
      - ../config/match-service.env
    depends_on:
      gateway-service:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5              
              
  ###################
  ## Beta Frontend ##
  ###################

  beta-frontend:
    image: 040156513434.dkr.ecr.eu-west-1.amazonaws.com/beta-frontend:latest
    ports:
      - 3000:3000
    container_name: beta-frontend
