server:
  port: ${SERVER_PORT}

spring:
  application:
    profiles:
      active: 'aws'
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false

security:
  oauth2:
    access-token-validity-seconds: ${ACCESS_TOKEN_VALIDITY_SECONDS}
    refresh-token-validity-seconds: ${REFRESH_TOKEN_VALIDITY_SECONDS}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    public-key: ${PUBLIC_KEY}
    private-key: ${PRIVATE_KEY}
