on:
  workflow_call:
    inputs:
      LIB_NAME:
        required: true
        type: string
      RELEASE:
        type: string
        default: "false"
      SLACK_NOTIFICATION:
        type: string
        default: "false"

jobs:
  main-workflow:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Version generation
        run: |
          cd libs/${{ inputs.LIB_NAME }}
          if [[ ${{ inputs.RELEASE }} == true ]]; then
            echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi
        shell: bash

      - name: lib pipeline
        uses: ./.github/actions/action-mvn-build
        with:
          PATH: libs
          NAME: ${{ inputs.LIB_NAME }}
          VERSION: ${{ env.VERSION }}
          SLACK_NOTIFICATION: ${{ inputs.SLACK_NOTIFICATION }}
          AWS_ECR_URI: ${{ secrets.AWS_ECR_URI }}
          AWS_CICD_ACCESS_KEY: ${{ secrets.AWS_CICD_ACCESS_KEY }}
          AWS_CICD_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_SECRET_ACCESS_KEY }}
          DOCKER_IMAGE_GENERATION: false
