name: Services Workflow

run-name: ${{ github.actor }} fired services workflow

on:
  workflow_dispatch:
  push:

jobs:
  main-workflow:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "maven"

      - uses: ./.github/actions/action-mvn-build
        with:
          path: "services/auth-service"
          service-name: "auth-service"
