name: Services Workflow

run-name: ${{ github.actor }} fired services workflow

on:
  push:
    paths:
      - 'services/**'
      - '.github/workflows/main.yml'

jobs:

  main-workflow:

    runs-on: ubuntu-20.04

    steps:

      - uses: actions/action-mvn-build
        with:
          path: 'services/auth-service'
