name: main_auth-service.yml

run-name: ${{ github.actor }} fired main workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "services/auth-service/**"

jobs:
  main-workflow:
    uses: ./.github/workflows/default_main_mvn_service.yml
    secrets: inherit
    with:
      SERVICE_NAME: "auth-service"
       