name: Services Workflow

run-name: ${{ github.actor }} fired services workflow

on:
  push:
    paths:
      - 'services/**'
      - '.github/workflows/main.yml'

jobs:

  main-workflow:

    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - run: |
          echo '1'
          ls
          echo '2'
          cd services/auth-service
          echo '3'
          ls

      - name: Build
        run: mvn clean install -U
