name: player-service.yml

on:
  pull_request:
    paths:
      - "services/player-service/**"
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
    paths:
      - "services/player-service/**"

jobs:

  merge-request-job:
    uses: ./.github/workflows/default_mvn_service.yml
    if: github.event_name == 'pull_request'
    secrets: inherit
    with:
      SERVICE_NAME: "player-service"
      DOCKER_IMAGE_GENERATION: "false"

  push-main-job:
    uses: ./.github/workflows/default_mvn_service.yml
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    secrets: inherit
    with:
      SERVICE_NAME: "player-service"
       
  tag-job:
    uses: ./.github/workflows/default_mvn_service.yml
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    secrets: inherit
    with:
      SERVICE_NAME: "player-service"
      RELEASE: "true"
