version: '3'

services:

  notifications-service:
    image: rust:1.65
    container_name: notifications-service
    env_file:
      - ../../config/notifications-service.env
    volumes:
      - ${CARGO_PATH}/registry:/usr/local/cargo/registry
      - ../../services/notifications-service:/notifications-service
    working_dir: /notifications-service
    command: cargo run
